---
apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: hello-world-app
description: Hello World Deployment Pipeline 
serialPipeline:
  stages:
  - targetId: staging
  - targetId: production

---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: staging
description: Staging Environment
gke:
  cluster: projects/yougo-dev-369515/locations/us-west1/clusters/ugo-dev-cluster

---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: production
description: Production Environment
gke:
  cluster: projects/yougo-prod-369515/locations/us-west1/clusters/ugo-prod-cluster
